version: 1.0.0.{build}
image: Visual Studio 2019
configuration: Debug
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore
build_script:
- cmd: dotnet build ZbW.Testing.WpfSample.sln
artifacts:
  - path: ZbW.Testing.WpfSample.Client\bin\$(configuration)\netcoreapp3.1
    name: ZbW.WpfSample
